### ISSUE TITLE
Game Crash when loading

### ISSUE THREAD

**Issue by LegacyyRL** [Ilyaki/TerrariaSplitScreen#3]
for some reason when i load the game, without any other mods it crashes
![image](https://user-images.githubusercontent.com/28121219/42712507-dfc2d3f8-86e3-11e8-9e22-6f8cbb98a817.png)

**Comment by Ilyaki** [comment]
Can you try restarting the game a few times to see if it happens every time?
Do you have any anti-virus programs that might be blocking the mod? If you do, try adding an exception.

**Comment by LegacyyRL** [comment]
For some reason if I reinstall it it will fix, but if i add or remove any mods whilst it's installed it will crash until I reinstall it

**Comment by Ilyaki** [comment]
When you enable/disable the mod, make sure to restart the game fully - I think there are some issues with mod reload.

**Comment by LegacyyRL** [comment]
Thank you :)
